# Generated by Django 3.2 on 2022-03-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_search', '0002_auto_20220308_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
