# Generated by Django 3.2 on 2022-03-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_search', '0004_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
