# Generated by Django 3.2 on 2022-03-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_search', '0005_auto_20220315_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rode',
            new_name='role',
        ),
    ]
